### ISSUE TITLE
 Tensor conversion requested dtype int32 for Tensor with dtype float32: 

### ISSUE THREAD

**Issue by skywo1f** [Guanghan/ROLO#51]
ValueError: Tensor conversion requested dtype int32 for Tensor with dtype float32: 'Tensor("Reshape:0", shape=(3, 4102), dtype=float32, device=/device:GPU:0)'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./experiments/testing/ROLO_network_test_all.py", line 275, in <module>
    main(' ')
  File "./experiments/testing/ROLO_network_test_all.py", line 271, in main
    ROLO_TF(argvs)
  File "./experiments/testing/ROLO_network_test_all.py", line 95, in __init__
    self.ROLO(argvs)
  File "./experiments/testing/ROLO_network_test_all.py", line 235, in ROLO
    self.build_networks()
  File "./experiments/testing/ROLO_network_test_all.py", line 127, in build_networks
    self.lstm_module = self.LSTM_single('lstm_test', self.x, self.istate, self.weights, self.biases)
  File "./experiments/testing/ROLO_network_test_all.py", line 105, in LSTM_single
    _X = tf.split(0, self.num_steps, _X) # n_steps * (batch_size, num_input)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/array_ops.py", line 1563, in split
    axis=axis, num_split=num_or_size_splits, value=value, name=name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/gen_array_ops.py", line 9496, in split
    "Split", split_dim=axis, value=value, num_split=num_split, name=name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/op_def_library.py", line 550, in _apply_op_helper
    (prefix, dtypes.as_dtype(input_arg.type).name))
TypeError: Input 'split_dim' of 'Split' Op has type float32 that does not match expected type of int32.

**Comment by skywo1f** [comment]
https://stackoverflow.com/questions/41842440/tensorflow-input-split-dim-of-split-op-has-type-float32-that-does-not-matc
