### ISSUE TITLE
TypeError: Input 'split_dim' of 'Split' Op has type float32 that does not match expected type of int32.

### ISSUE THREAD

**Issue by TessaJoseIgn** [Guanghan/ROLO#54]
Hi, I am getting the following error
TRAINING ROLO...
Traceback (most recent call last):
  File "/home/###/threads/$$/venv/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 510, in _apply_op_helper
    preferred_dtype=default_dtype)
  File "/home/###/threads/$$/venv/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1146, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/home/###/threads/$$/venv/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 983, in _TensorTensorConversionFunction
    (dtype.name, t.dtype.name, str(t)))
ValueError: Tensor conversion requested dtype int32 for Tensor with dtype float32: 'Tensor("Reshape:0", shape=(6, 4102), dtype=float32)'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "experiments/training/ROLO_step6_train_20_exp1.py", line 332, in <module>
    main(' ')
  File "experiments/training/ROLO_step6_train_20_exp1.py", line 329, in main
    ROLO_TF(argvs)
  File "experiments/training/ROLO_step6_train_20_exp1.py", line 95, in __init__
    self.ROLO(argvs)
  File "experiments/training/ROLO_step6_train_20_exp1.py", line 325, in ROLO
    self.train_20()
  File "experiments/training/ROLO_step6_train_20_exp1.py", line 222, in train_20
    self.build_networks()
  File "experiments/training/ROLO_step6_train_20_exp1.py", line 134, in build_networks
    self.lstm_module = self.LSTM_single('lstm_test', self.x, self.istate, self.weights, self.biases)
  File "experiments/training/ROLO_step6_train_20_exp1.py", line 105, in LSTM_single
    _X = tf.split(0, self.num_steps, _X) # n_steps * (batch_size, num_input)
  File "/home/###/threads/$$/venv/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 1327, in split
    axis=axis, num_split=num_or_size_splits, value=value, name=name)
  File "/home/###/threads/$$/venv/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 8083, in split
    "Split", split_dim=axis, value=value, num_split=num_split, name=name)
  File "/home/###/threads/$$/venv/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 533, in _apply_op_helper
    (prefix, dtypes.as_dtype(input_arg.type).name))
TypeError: Input 'split_dim' of 'Split' Op has type float32 that does not match expected type of int32.

**Comment by Niveditakatta** [comment]
Refer to this: https://github.com/tensorflow/tensorflow/issues/6501

**Comment by 0xVortex** [comment]
Change this part:
`_X = tf.split(0, self.num_steps, _X) `

to this:
`_X = tf.split(_X, self.num_steps, 0) `
